env:
   global:
     - CONAN_TOTAL_PAGES=4
osx: &osx
   os: osx
   language: generic

# bincrafters-conventions:no-new-compiler-versions  
# Qt only needs to get build with one compiler version on macOS

matrix:
   include:
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_CURRENT_PAGE=1
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_CURRENT_PAGE=2
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_CURRENT_PAGE=3
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_CURRENT_PAGE=4

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh
script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
